# **Import Library**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# **Import Data**

In [ ]:
df=pd.read_csv('/content/auto-mpg.csv')

In [ ]:
df.head()

mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   
3  16.0          8         304.0        150    3433          12.0          70   
4  17.0          8         302.0        140    3449          10.5          70   

   origin  
0       1  
1       1  
2       1  
3       1  
4       1

In [ ]:
df.nunique()

mpg             129
cylinders         5
displacement     82
horsepower       94
weight          351
acceleration     95
model year       13
origin            3
dtype: int64

# **Data Processing**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object 
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64  
 7   origin        398 non-null    int64  
dtypes: float64(3), int64(4), object(1)
memory usage: 25.0+ KB


In [ ]:
df.describe()

mpg   cylinders  displacement       weight  acceleration  \
count  398.000000  398.000000    398.000000   398.000000    398.000000   
mean    23.514573    5.454774    193.425879  2970.424623     15.568090   
std      7.815984    1.701004    104.269838   846.841774      2.757689   
min      9.000000    3.000000     68.000000  1613.000000      8.000000   
25%     17.500000    4.000000    104.250000  2223.750000     13.825000   
50%     23.000000    4.000000    148.500000  2803.500000     15.500000   
75%     29.000000    8.000000    262.000000  3608.000000     17.175000   
max     46.600000    8.000000    455.000000  5140.000000     24.800000   

       model year      origin  
count  398.000000  398.000000  
mean    76.010050    1.572864  
std      3.697627    0.802055  
min     70.000000    1.000000  
25%     73.000000    1.000000  
50%     76.000000    1.000000  
75%     79.000000    2.000000  
max     82.000000    3.000000

In [ ]:
df['horsepower'].unique()

array(['130', '165', '150', '140', '198', '220', '215', '225', '190',
       '170', '160', '95', '97', '85', '88', '46', '87', '90', '113',
       '200', '210', '193', '70', '100', '105', '175', '153', '180',
       '110', '72', '86', '76', '65', '69', '60', '80', '54', '208',
       '155', '112', '92', '145', '137', '158', '167', '94', '107', '230',
       '49', '75', '91', '122', '?', '67', '83', '78', '52', '61', '93',
       '148', '129', '96', '71', '98', '115', '53', '81', '79', '120',
       '152', '102', '108', '68', '58', '149', '89', '63', '48', '66',
       '139', '103', '125', '133', '138', '135', '142', '77', '62', '132',
       '84', '64', '74', '116', '82'], dtype=object)

In [ ]:
df['horsepower']=df['horsepower'].str.replace('?','70')

In [ ]:
df['horsepower']=df['horsepower'].astype(int)

In [ ]:
df.corr()

mpg  cylinders  displacement  horsepower    weight  \
mpg           1.000000  -0.775396     -0.804203   -0.774583 -0.831741   
cylinders    -0.775396   1.000000      0.950721    0.842838  0.896017   
displacement -0.804203   0.950721      1.000000    0.896655  0.932824   
horsepower   -0.774583   0.842838      0.896655    1.000000  0.862894   
weight       -0.831741   0.896017      0.932824    0.862894  1.000000   
acceleration  0.420289  -0.505419     -0.543684   -0.688745 -0.417457   
model year    0.579267  -0.348746     -0.370164   -0.416474 -0.306564   
origin        0.563450  -0.562543     -0.609409   -0.446896 -0.581024   

              acceleration  model year    origin  
mpg               0.420289    0.579267  0.563450  
cylinders        -0.505419   -0.348746 -0.562543  
displacement     -0.543684   -0.370164 -0.609409  
horsepower       -0.688745   -0.416474 -0.446896  
weight           -0.417457   -0.306564 -0.581024  
acceleration      1.000000    0.288137  0.205873  
model year        0.288137    1.000000  0.180662  
origin            0.205873    0.180662  1.000000

# **Removing Missing Values**

In [ ]:
df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
dtype: int64

In [ ]:
df=df.dropna()

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    int64  
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64  
 7   origin        398 non-null    int64  
dtypes: float64(3), int64(5)
memory usage: 25.0 KB


# **Data Visualization**

In [ ]:
sns.pairplot(df,x_vars=['displacement','horsepower','weight','acceleration','mpg'],y_vars=['mpg'])

In [ ]:
sns.regplot(x='displacement',y='mpg',data=df)

<Axes: xlabel='displacement', ylabel='mpg'>

# **Define Target Variable y and Feature X**

In [ ]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model year', 'origin'],
      dtype='object')

In [ ]:
y=df['mpg']

In [ ]:
y.shape

(398,)

In [ ]:
X=df[['displacement','horsepower','weight','acceleration']]

In [ ]:
X.shape

(398, 4)

In [ ]:
X

displacement  horsepower  weight  acceleration
0           307.0         130    3504          12.0
1           350.0         165    3693          11.5
2           318.0         150    3436          11.0
3           304.0         150    3433          12.0
4           302.0         140    3449          10.5
..            ...         ...     ...           ...
393         140.0          86    2790          15.6
394          97.0          52    2130          24.6
395         135.0          84    2295          11.6
396         120.0          79    2625          18.6
397         119.0          82    2720          19.4

[398 rows x 4 columns]

# **Scaling Data**

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler=StandardScaler()

In [ ]:
X=scaler.fit_transform(X)

In [ ]:
X

array([[ 1.0906037 ,  0.67871579,  0.63086987, -1.29549834],
       [ 1.5035143 ,  1.5906092 ,  0.85433297, -1.47703779],
       [ 1.19623199,  1.19979774,  0.55047045, -1.65857724],
       ...,
       [-0.56103873, -0.5197727 , -0.79858454, -1.4407299 ],
       [-0.70507731, -0.65004319, -0.40841088,  1.10082237],
       [-0.71467988, -0.5718809 , -0.29608816,  1.39128549]])

In [ ]:
pd.DataFrame(X).describe()

0             1             2             3
count  3.980000e+02  3.980000e+02  3.980000e+02  3.980000e+02
mean  -1.785283e-17  1.428227e-16 -1.606755e-16 -2.677925e-16
std    1.001259e+00  1.001259e+00  1.001259e+00  1.001259e+00
min   -1.204411e+00 -1.509828e+00 -1.604943e+00 -2.747814e+00
25%   -8.563178e-01 -7.542596e-01 -8.828266e-01 -6.328794e-01
50%   -4.314040e-01 -3.113399e-01 -1.973624e-01 -2.472221e-02
75%    6.584879e-01  5.484453e-01  7.538337e-01  5.834349e-01
max    2.511784e+00  3.284126e+00  2.565185e+00  3.351912e+00

# *After Standardization mean=1 and standard deviaion =0*

# **Train Test Split**

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=2529)

In [ ]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((278, 4), (120, 4), (278,), (120,))

# **Linear Regression Model**

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
regressor=LinearRegression()

In [ ]:
regressor.fit(X_train,y_train)

LinearRegression()

In [ ]:
regressor.coef_

array([-1.07215487, -1.40876281, -4.4525717 , -0.25380634])

In [ ]:
regressor.intercept_

23.513770806869456

**Mileage = 23.51 - 1.07 displacement - 1.40 horsepower - 4.45 weight - 0.25 acceleration**

# **Predict Test Data**

In [ ]:
y_pred=regressor.predict(X_test)

In [ ]:
y_pred

array([15.65491431, 30.72847508, 18.91262642, 24.14880664, 32.44831537,
       29.58838853, 25.26935727, 12.42903263,  9.16574407, 28.74108686,
       30.76220046, 20.82063108, 31.77625715, 14.77985543, 20.54303376,
       15.23885262, 24.52491309, 32.07808   , 14.60069649, 11.34600438,
       18.51094268, 30.25467248, 27.06818419, 18.90813753, 20.27707727,
       26.12034722, 32.1564369 , 30.36417428,  9.23325108, 25.47785827,
        8.03058472, 26.88308357, 31.02125566, 21.17348895, 16.28238089,
       21.18546247,  9.56290962, 23.44818444, 30.96725671, 33.50021592,
       25.96840384, 31.16095451, 27.59496607, 18.60955807, 22.21702381,
       25.77118996, 20.6896248 , 29.67302673, 23.51884955, 24.4843701 ,
       27.7347256 , 12.80302225, 22.86181215, 32.6076105 , 19.09973075,
       14.06503346, 30.98204816, 26.73830051, 21.19485097, 30.05091686,
       23.51310038, 30.85020537, 23.13668333,  8.69780659, 31.44352198,
       19.73935957, 27.57333075, 21.48835708, 11.29116067, 28.41

# **Model Accuracy**

In [ ]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [ ]:
mse=mean_squared_error(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
rmse=np.sqrt(mse)
r_squared=r2_score(y_test,y_pred)

In [ ]:
print(f'Mean Squared Error is: {mse}')
print(f'Mean Absolute Error is: {mae}')
print(f'Root Mean Square Error is: {rmse}')
print(f'RSquared is: {r_squared}')

Mean Squared Error is: 21.93393100886519
Mean Absolute Error is: 3.52107175982914
Root Mean Square Error is: 4.683367485993939
RSquared is: 0.6672618162158979


# **Polynomial Regression**

In [ ]:
from sklearn.preprocessing import PolynomialFeatures

In [ ]:
poly=PolynomialFeatures()

In [ ]:
X_train2=poly.fit_transform(X_train)

In [ ]:
X_test2=poly.fit_transform(X_test)

In [ ]:
regressor.fit(X_train2,y_train)

LinearRegression()

In [ ]:
regressor.intercept_

22.093583936867745

In [ ]:
regressor.coef_

array([ 0.        , -2.45025748, -4.07477311, -2.16182223, -0.89749265,
       -5.75760232,  6.0498497 ,  6.14463763, -0.88930879, -1.48459656,
       -0.52954533,  0.23730806, -2.18758349,  1.32674665,  0.26412527])

In [ ]:
y_pred_poly=regressor.predict(X_test2)

# **Model Accuracy**

In [ ]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score,mean_absolute_percentage_error

In [ ]:
mean_absolute_error(y_test,y_pred_poly)

3.03031312940957

In [ ]:
mean_squared_error(y_test,y_pred_poly)

21.02684132348403

In [ ]:
mean_absolute_percentage_error(y_test,y_pred_poly)

0.12625917569008668

In [ ]:
r2_score(y_test,y_pred_poly)

0.6810223853688249